#define MATRIX_ROWS 6
#define MATRIX_COLS 12
#define RGB_MATRIX_LED_COUNT 66
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 120
#define RGB_MATRIX_SLEEP
//#define RGB_MATRIX_TIMEOUT 300000     // 5 minutes (5 * 60 * 1000ms)

#define WS2812_BYTE_ORDER WS2812_BYTE_ORDER_GRB
#define WS2812_DI_PIN GP4

#define RGB_MATRIX_DEFAULT_ON true         // LEDs turn on by default
#define RGB_MATRIX_DEFAULT_MODE 1

#define ENABLE_RGB_MATRIX_BREATHING
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
